version: "3"

services:
  datagenerator:
    build: .
    ports:
      - "5000:5000"
  nifi:
    image: apache/nifi:latest
    ports:
      - "8081:8081"
    volumes:
      - ~/document/Nifi/shared-directory:/opt/nifi/nifi-current/ls-targe
    environment:
      - NIFI_WEB_HTTP_PORT=8081
  clickhouse1:
    image: clickhouse/clickhouse-server
    hostname: ch1
    container_name: ch1
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./ch1_config/ckeeper_config.xml:/etc/clickhouse-server/config.d/ckeeper_config.xml
      - ./ch1_config/cluster_definition_config.xml:/etc/clickhouse-server/config.d/cluster_definition_config.xml
      - ./ch1_config/external_listen_config.xml:/etc/clickhouse-server/config.d/external_listen_config.xml
      - ./ch1_config/macros_config.xml:/etc/clickhouse-server/config.d/macros_config.xml
      - ./ch1_config/default_grants_config.xml:/etc/clickhouse-server/users.d/default_grants_config.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  keeper1:
    image: clickhouse/clickhouse-server
    hostname: keeper1
    container_name: keeper1
    volumes:
      - ./keeper1_config/external_listen_config.xml:/etc/clickhouse-server/config.d/external_listen_config.xml
      - ./keeper1_config/keeper1_config.xml:/etc/clickhouse-server/config.d/keeper1_config.xml
    ports:
      - "9004:9000"
      - "9181:9181"
      - "9234:9234"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"

  kafka:
    image: bitnami/kafka:3.4.1
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./data/kafka:/bitnami/kafka
